name: gchm

channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - ipython
  - matplotlib
  - numpy
  - wandb
  - pathlib
  - tqdm
  - botocore
  - urllib3
  - wandb
  - tensorboard
  - sentinelhub=3.9.0
  - anaconda::scikit-image
  - anaconda::scikit-learn
  - anaconda::typing
  - anaconda::jupyter
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - gdal=3.6.2
  - pytables
  - pip
  - pip:
    - -e .

