name: gchm

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python>=3.12.0
  - r-base>=4.4.0
  - gdal
  - sentinelhub
  - pytables
  - libgdal-jp2openjpeg
  - ipython
  - matplotlib
  - numpy
  - pathlib
  - tqdm
  - botocore
  - urllib3
  - wandb
  - tensorboard
  - scikit-image
  - scikit-learn
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::cudatoolkit==11.8.0
  - typing
  - jupyter
  - r-terra
  - r-sf
  - r-tmap
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-plyr
  - r-dplyr
  - r-leaflet
  - r-viridis
  - r-cols4all
  - r-colorspace
  - r-codetools
  - pip
  - pip:
    - -e .
