name: gchm

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.10.9
  - r-base>4.4.0
  - gdal
  - pytables
  - ipython
  - matplotlib
  - numpy
  - pathlib
  - tqdm
  - botocore
  - urllib3
  - scikit-image
  - scikit-learn
  - typing
  - jupyter
  - cudatoolkit
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - r-terra
  - r-sf
  - r-tmap
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-plyr
  - r-dplyr
  - r-leaflet
  - r-viridis
  - r-cols4all
  - r-colorspace
  - pip
  - pip:
    - -e .
