---
title: "Setup gchm | virtual environments"
author: "ESA99"
format: html
---

## Installation

The original [Installation guide](https://github.com/langnico/global-canopy-height-model#installation-and-credentials) by Nico Lang's [global-canopy-height](https://langnico.github.io/globalcanopyheight) model proofed to be difficult to adapt locally and implement correctly. The suggested *mambaforge* is outdated and should be replaced with *miniforge3*. Following the installation steps and trying to install it with the specified versions leads to environment problems and dependency issues. It is to be prefered to use the environment.yml file for the full installation with a few minor changes and trapdoors to watch out for:

**miniforge3** is installed via `Miniforge3-Linux-x86_64.sh` Important: Solver has to be set to **libmamba**. Classic solver is outdated and takes hours to solve. Check via <conda info>. If not change it like this:

``` bash
conda config --set solver libmamba
```

Then we can install the virtual environment from the `environment.yml` file, that specifies our requirements. See [environment.yml](#environment.yml) for details. This creates the virtual environment, giving it the name specified in the file. Then it sorts out which versions work with each other and set's up everything.

``` bash
mamba env create -f environment.yml
```

The other way to setup the virtual environment is via the `requirements.txt` file. Here the exact versions are specified and all contents included (like dependencies), while `environment.yml` only includes the desired requirements and then solves the rest.

These are the versions after the successful installation on Linux EndevourOS on 14.10.2025:

``` bash
conda version : 24.11.3
solver : libmamba (default)
python version : 3.12.9.final.0
virtual packages : __archspec=1=zen4
                          __conda=24.11.3=0
                          __cuda=13.0=0
                          __glibc=2.42=0
                          __linux=6.17.1=0
                          __unix=0=0

```

To see all installed software and packagaes with their exact version use `conda list` or filter for a specific item
``` bash
conda list

conda list | grep numpy
```

This is part of the final environment:
``` bash
gdal                      3.11.4          py312hf50df08_4    conda-forge

proj                      9.7.0                hb72c0af_0    conda-forge

r-base                    4.5.1                h14df4e6_3    conda-forge

pytables                  3.10.2          py312hefc0c3f_9    conda-forge
python                    3.12.12         hfe2f287_0_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhe01879c_2    conda-forge
python-fastjsonschema     2.21.2             pyhe01879c_0    conda-forge
python-gil                3.12.12              hd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    8_cp312    conda-forge
pytorch                   2.4.0           py3.12_cuda12.4_cudnn9.1.0_0    pytorch
pytorch-cuda              12.4                 hc786d27_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch

torchaudio                2.4.0               py312_cu124    pytorch
torchtriton               3.0.0                     py312    pytorch
torchvision               0.19.0              py312_cu124    pytorch

libtiff                   4.7.1                h8261f1e_0    conda-forge

sentinelhub               3.11.3             pyhd8ed1ab_0    conda-forge

tensorboard               2.20.0             pyhe01879c_0    conda-forge

```

Other system libraries may be installed additionally globally.
In the first setup run after the original suggestion, libtiff version were an issue -> Ex.: libtiff 5 was required but only other versions installed.
The do


## Deployment

To run the model use the following code inside the terminal. Beforehand set all the variables inside the script `deploy.R` and make sure all image folders are in the correct place and named correctly (Tile name without "T": "49UCP").

``` bash
conda activate gchm
cd /home/emilio/canopy_height/
Rscript deploy.R
```

With the lat-lon implementation:

``` bash
conda activate gchm
cd ./canopy_height
Rscript R/latlong/deploy_latlong.R
```

### Usefull bash code

Real time GPU supervision:

``` bash
watch -n 1 nvidia-smi
```

## environment.yml {#environment.yml}

The environment.yml file contains all info about what we want to install and tells conda our requirements. The solver then sorts out the correct versions for the virtual environment to work with each other. It works from top to bottom. **gdal** is included here; the version will fit to the required python and R. We included **R** here as well to have a fully encapsulated environment ensuring compatibility, instead of deploying scripts from outside the branch.

``` bash
name: gchm

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python>=3.12.0
  - r-base>=4.4.0
  - gdal
  - sentinelhub
  - pytables
  - libgdal-jp2openjpeg
  - ipython
  - matplotlib
  - numpy
  - pathlib
  - tqdm
  - botocore
  - urllib3
  - wandb
  - tensorboard
  - scikit-image
  - scikit-learn
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::cudatoolkit==11.8.0
  - typing
  - jupyter
  - pip
  - pip:
    - -e .
```

``` bash
# packages in environment at /home/emilio/miniforge3/envs/gchm:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                  4_kmp_llvm    conda-forge
_python_abi3_support      1.0                  hd8ed1ab_2    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
absl-py                   2.3.1              pyhd8ed1ab_0    conda-forge
aenum                     3.1.15             pyhd8ed1ab_1    conda-forge
alsa-lib                  1.2.14               hb9d3cd8_0    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_1    conda-forge
anyio                     4.11.0             pyhcf101f3_0    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
appdirs                   1.4.4              pyhd8ed1ab_1    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      25.1.0          py312h4c3975b_1    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attr                      2.5.2                h39aace5_0    conda-forge
attrs                     25.4.0             pyh71513ae_0    conda-forge
babel                     2.17.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.14.2             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.44                 hdf8817f_2    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    6.2.0              pyh29332c3_4    conda-forge
bleach-with-css           6.2.0                h82add2a_4    conda-forge
blinker                   1.9.0              pyhff2d567_0    conda-forge
blosc                     1.21.6               he440d0b_1    conda-forge
boto3                     1.40.51            pyhd8ed1ab_0    conda-forge
botocore                  1.40.51            pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb03c661_4    conda-forge
brotli-bin                1.1.0                hb03c661_4    conda-forge
brotli-python             1.1.0           py312h1289d80_4    conda-forge
brunsli                   0.1                  he3183e4_1    conda-forge
bwidget                   1.10.1               ha770c72_1    conda-forge
bzip2                     1.0.8                hda65f42_8    conda-forge
c-ares                    1.34.5               hb9d3cd8_0    conda-forge
c-blosc2                  2.21.3               h4cfbee9_0    conda-forge
ca-certificates           2025.10.5            hbd8a1cb_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.4               h3394656_0    conda-forge
certifi                   2025.10.5          pyhd8ed1ab_0    conda-forge
cffi                      2.0.0           py312h35888ee_0    conda-forge
charls                    2.4.2                h59595ed_0    conda-forge
charset-normalizer        3.4.4              pyhd8ed1ab_0    conda-forge
click                     8.3.0              pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
comm                      0.2.3              pyhe01879c_0    conda-forge
contourpy                 1.3.3           py312hd9148b4_2    conda-forge
cpython                   3.12.12         py312hd8ed1ab_0    conda-forge
cryptography              46.0.2          py312hee9fe19_0    conda-forge
cuda-cudart               12.4.127                      0    nvidia
cuda-cupti                12.4.127                      0    nvidia
cuda-libraries            12.4.1               ha770c72_1    conda-forge
cuda-nvrtc                12.4.127                      0    nvidia
cuda-nvtx                 12.4.127                      0    nvidia
cuda-opencl               12.4.127                      0    nvidia
cuda-runtime              12.4.1               ha804496_0    conda-forge
cudatoolkit               11.8.0              h4ba93d1_13    conda-forge
curl                      8.14.1               h332b0f4_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
cyrus-sasl                2.1.28               hd9c7081_0    conda-forge
dataclasses-json          0.6.7              pyhd8ed1ab_1    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
dbus                      1.16.2               h3c4dab8_0    conda-forge
debugpy                   1.8.17          py312h8285ef7_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
double-conversion         3.3.1                h5888daf_0    conda-forge
editables                 0.5                pyhd8ed1ab_1    conda-forge
eval_type_backport        0.2.2              pyha770c72_0    conda-forge
exceptiongroup            1.3.0              pyhd8ed1ab_0    conda-forge
executing                 2.2.1              pyhd8ed1ab_0    conda-forge
ffmpeg                    8.0.0           gpl_hbbdf940_906    conda-forge
filelock                  3.20.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h7e30c49_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.60.1          py312h8a5da7c_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_1    conda-forge
freetype                  2.14.1               ha770c72_0    conda-forge
freexl                    2.0.0                h9dce30a_2    conda-forge
fribidi                   1.0.16               hb03c661_0    conda-forge
gcc_impl_linux-64         15.2.0               hcacfade_7    conda-forge
gchm                      1.0                      pypi_0    pypi
gdal                      3.11.4          py312hf50df08_4    conda-forge
gdk-pixbuf                2.44.3               h2b0a6b4_0    conda-forge
geos                      3.14.0               h480dda7_0    conda-forge
gettext                   0.25.1               h3f43e3d_1    conda-forge
gettext-tools             0.25.1               h3f43e3d_1    conda-forge
gfortran_impl_linux-64    15.2.0               h1b0a18f_7    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
gitdb                     4.0.12             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.45             pyhff2d567_0    conda-forge
glslang                   16.0.0               hfd11570_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.2.1           py312hcaba1f9_1    conda-forge
graphite2                 1.3.14               hecca717_2    conda-forge
grpcio                    1.74.1          py312h6f3464c_1    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gxx_impl_linux-64         15.2.0               h54ccb8d_7    conda-forge
h11                       0.16.0             pyhd8ed1ab_0    conda-forge
h2                        4.3.0              pyhcf101f3_0    conda-forge
harfbuzz                  12.1.0               h15599e2_0    conda-forge
hatchling                 1.27.0           pypyhd8ed1ab_0    conda-forge
hdf5                      1.14.6          nompi_h6e4c0c1_103    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
httpcore                  1.0.9              pyh29332c3_0    conda-forge
httpx                     0.28.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.11               pyhd8ed1ab_0    conda-forge
imagecodecs               2025.8.2        py312h4ecb025_4    conda-forge
imageio                   2.37.0             pyhfb79c49_0    conda-forge
importlib-metadata        8.7.0              pyhe01879c_1    conda-forge
intel-gmmlib              22.8.2               hb700be7_0    conda-forge
intel-media-driver        25.3.4               hecca717_0    conda-forge
ipykernel                 7.0.0              pyha191276_0    conda-forge
ipython                   9.6.0              pyhfa0c392_0    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
ipywidgets                8.1.7              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_1    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_1    conda-forge
joblib                    1.5.2              pyhd8ed1ab_0    conda-forge
json-c                    0.18                 h6688a6e_0    conda-forge
json5                     0.12.1             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h7900ff3_2    conda-forge
jsonschema                4.25.1             pyhe01879c_0    conda-forge
jsonschema-specifications 2025.9.1           pyhcf101f3_0    conda-forge
jsonschema-with-format-nongpl 4.25.1               he01879c_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_1    conda-forge
jupyter-lsp               2.3.0              pyhcf101f3_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.8.1              pyh31011fe_0    conda-forge
jupyter_events            0.12.0             pyh29332c3_0    conda-forge
jupyter_server            2.17.0             pyhcf101f3_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_1    conda-forge
jupyterlab                4.4.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_2    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.15             pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  hd590300_3    conda-forge
kernel-headers_linux-64   5.14.0               he073ed8_2    conda-forge
keyutils                  1.6.3                hb9d3cd8_0    conda-forge
kiwisolver                1.4.9           py312h0a2e395_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lark                      1.3.0              pyhd8ed1ab_0    conda-forge
lazy-loader               0.4                pyhd8ed1ab_2    conda-forge
lcms2                     2.17                 h717163a_0    conda-forge
ld_impl_linux-64          2.44                 ha97dd6f_2    conda-forge
lerc                      4.0.0                h0aef613_1    conda-forge
level-zero                1.24.3               hb700be7_0    conda-forge
libabseil                 20250512.1      cxx17_hba17884_0    conda-forge
libaec                    1.1.4                h3f801dc_0    conda-forge
libarchive                3.8.1           gpl_h7be2006_101    conda-forge
libasprintf               0.25.1               h3f43e3d_1    conda-forge
libasprintf-devel         0.25.1               h3f43e3d_1    conda-forge
libass                    0.17.4               h96ad9f0_0    conda-forge
libavif16                 1.3.0                h6395336_2    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libbrotlicommon           1.1.0                hb03c661_4    conda-forge
libbrotlidec              1.1.0                hb03c661_4    conda-forge
libbrotlienc              1.1.0                hb03c661_4    conda-forge
libcap                    2.76                 h0b2e76d_0    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libclang-cpp21.1          21.1.3          default_h99862b1_0    conda-forge
libclang13                21.1.3          default_h746c552_0    conda-forge
libcublas                 12.4.5.8                      0    nvidia
libcufft                  11.2.1.3                      0    nvidia
libcufile                 1.9.1.3                       0    nvidia
libcups                   2.3.3                hb8b1518_5    conda-forge
libcurand                 10.3.5.147                    0    nvidia
libcurl                   8.14.1               h332b0f4_0    conda-forge
libcusolver               11.6.1.9                      0    nvidia
libcusparse               12.3.1.170                    0    nvidia
libdeflate                1.24                 h86f0d12_0    conda-forge
libdrm                    2.4.125              hb03c661_1    conda-forge
libedit                   3.1.20250104    pl5321h7949ede_0    conda-forge
libegl                    1.7.0                ha4b6fd6_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.7.1                hecca717_0    conda-forge
libffi                    3.4.6                h2dba641_1    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libfreetype               2.14.1               ha770c72_0    conda-forge
libfreetype6              2.14.1               h73754d4_0    conda-forge
libgcc                    15.2.0               h767d61c_7    conda-forge
libgcc-devel_linux-64     15.2.0             h73f6952_107    conda-forge
libgcc-ng                 15.2.0               h69a702a_7    conda-forge
libgcrypt-lib             1.11.1               hb9d3cd8_0    conda-forge
libgdal-core              3.11.4               habfead2_4    conda-forge
libgdal-jp2openjpeg       3.11.4               hdd07572_4    conda-forge
libgettextpo              0.25.1               h3f43e3d_1    conda-forge
libgettextpo-devel        0.25.1               h3f43e3d_1    conda-forge
libgfortran               15.2.0               h69a702a_7    conda-forge
libgfortran-ng            15.2.0               h69a702a_7    conda-forge
libgfortran5              15.2.0               hcd61629_7    conda-forge
libgl                     1.7.0                ha4b6fd6_2    conda-forge
libglib                   2.86.0               h1fed272_0    conda-forge
libglvnd                  1.7.0                ha4b6fd6_2    conda-forge
libglx                    1.7.0                ha4b6fd6_2    conda-forge
libgomp                   15.2.0               h767d61c_7    conda-forge
libgpg-error              1.55                 h3f2d84a_0    conda-forge
libgrpc                   1.74.1               h3288cfb_1    conda-forge
libhwloc                  2.12.1          default_h7f8ec31_1002    conda-forge
libhwy                    1.3.0                h4c17acf_1    conda-forge
libiconv                  1.18                 h3b78370_2    conda-forge
libjpeg-turbo             3.1.0                hb9d3cd8_0    conda-forge
libjxl                    0.11.1               h6cb5226_4    conda-forge
libkml                    1.3.0             hf539b9f_1021    conda-forge
liblapack                 3.9.0            20_linux64_mkl    conda-forge
libllvm21                 21.1.3               hf7376ad_0    conda-forge
liblzma                   5.8.1                hb9d3cd8_2    conda-forge
libnghttp2                1.67.0               had1ee68_0    conda-forge
libnpp                    12.2.5.30                     0    nvidia
libnsl                    2.0.1                hb9d3cd8_1    conda-forge
libntlm                   1.8                  hb9d3cd8_0    conda-forge
libnvfatbin               12.4.127                      0    nvidia
libnvjitlink              12.4.127                      0    nvidia
libnvjpeg                 12.3.1.117                    0    nvidia
libogg                    1.3.5                hd0c01bc_1    conda-forge
libopengl                 1.7.0                ha4b6fd6_2    conda-forge
libopenvino               2025.2.0             hb617929_1    conda-forge
libopenvino-auto-batch-plugin 2025.2.0             hed573e4_1    conda-forge
libopenvino-auto-plugin   2025.2.0             hed573e4_1    conda-forge
libopenvino-hetero-plugin 2025.2.0             hd41364c_1    conda-forge
libopenvino-intel-cpu-plugin 2025.2.0             hb617929_1    conda-forge
libopenvino-intel-gpu-plugin 2025.2.0             hb617929_1    conda-forge
libopenvino-intel-npu-plugin 2025.2.0             hb617929_1    conda-forge
libopenvino-ir-frontend   2025.2.0             hd41364c_1    conda-forge
libopenvino-onnx-frontend 2025.2.0             h1862bb8_1    conda-forge
libopenvino-paddle-frontend 2025.2.0             h1862bb8_1    conda-forge
libopenvino-pytorch-frontend 2025.2.0             hecca717_1    conda-forge
libopenvino-tensorflow-frontend 2025.2.0             h0767aad_1    conda-forge
libopenvino-tensorflow-lite-frontend 2025.2.0             hecca717_1    conda-forge
libopus                   1.5.2                hd0c01bc_0    conda-forge
libpciaccess              0.18                 hb9d3cd8_0    conda-forge
libpng                    1.6.50               h421ea60_1    conda-forge
libpq                     18.0                 h3675c94_0    conda-forge
libprotobuf               6.31.1               h9ef548d_1    conda-forge
libre2-11                 2025.08.12           h7b12aa8_1    conda-forge
librsvg                   2.60.0               h61e6d4b_0    conda-forge
librttopo                 1.1.0               h96cd706_19    conda-forge
libsanitizer              15.2.0               hb13aed2_7    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libspatialite             5.1.0           gpl_hcb59c51_118    conda-forge
libsqlite                 3.50.4               h0c1763c_0    conda-forge
libssh2                   1.11.1               hcf80075_0    conda-forge
libstdcxx                 15.2.0               h8f9b012_7    conda-forge
libstdcxx-devel_linux-64  15.2.0             h73f6952_107    conda-forge
libstdcxx-ng              15.2.0               h4852527_7    conda-forge
libsystemd0               257.9                h996ca69_0    conda-forge
libtiff                   4.7.1                h8261f1e_0    conda-forge
libudev1                  257.9                h085a93f_0    conda-forge
libudunits2               2.2.28               h40f5838_3    conda-forge
libunwind                 1.8.3                h65a8314_0    conda-forge
liburing                  2.12                 hb700be7_0    conda-forge
libusb                    1.0.29               h73b1eb8_0    conda-forge
libuuid                   2.41.2               he9a06e4_0    conda-forge
libuv                     1.51.0               hb03c661_1    conda-forge
libva                     2.22.0               h4f16b4b_2    conda-forge
libvorbis                 1.3.7                h54a6638_2    conda-forge
libvpl                    2.15.0               h54a6638_1    conda-forge
libvpx                    1.14.1               hac33072_0    conda-forge
libvulkan-loader          1.4.328.1            h5279c79_0    conda-forge
libwebp-base              1.6.0                hd42ef1d_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.12.0               hca5e8e5_0    conda-forge
libxml2                   2.15.0               h26afc86_1    conda-forge
libxml2-16                2.15.0               ha9997c6_1    conda-forge
libxml2-devel             2.15.0               h26afc86_1    conda-forge
libxslt                   1.1.43               h711ed8c_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lz4-c                     1.10.0               h5888daf_1    conda-forge
lzo                       2.10              h280c20c_1002    conda-forge
make                      4.4.1                hb9d3cd8_2    conda-forge
markdown                  3.9                pyhd8ed1ab_0    conda-forge
markupsafe                3.0.3           py312h8a5da7c_0    conda-forge
marshmallow               3.26.1             pyhd8ed1ab_0    conda-forge
matplotlib                3.10.6          py312h7900ff3_1    conda-forge
matplotlib-base           3.10.6          py312he3d6523_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
minizip                   4.0.10               h05a5f5f_0    conda-forge
mistune                   3.1.4              pyhcf101f3_0    conda-forge
mkl                       2023.2.0         ha770c72_50498    conda-forge
mpc                       1.3.1                h24ddda3_1    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpg123                    1.32.9               hc50e24c_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_1    conda-forge
munkres                   1.1.4              pyhd8ed1ab_1    conda-forge
muparser                  2.3.5                h5888daf_0    conda-forge
mypy_extensions           1.1.0              pyha770c72_0    conda-forge
nbclient                  0.10.2             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.6             pyh29332c3_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_1    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
networkx                  3.5                pyhe01879c_0    conda-forge
notebook                  7.4.7              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_1    conda-forge
numexpr                   2.10.1          mkl_py312h791fadb_2    conda-forge
numpy                     2.3.3           py312h33ff503_0    conda-forge
oauthlib                  3.3.1              pyhd8ed1ab_0    conda-forge
ocl-icd                   2.3.3                hb9d3cd8_0    conda-forge
opencl-headers            2025.06.13           h5888daf_0    conda-forge
openh264                  2.6.0                hc22cd8d_0    conda-forge
openjpeg                  2.5.4                h55fea9a_0    conda-forge
openldap                  2.6.10               he970967_0    conda-forge
openssl                   3.5.4                h26f9b46_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_1    conda-forge
packaging                 25.0               pyh29332c3_1    conda-forge
pandoc                    3.8.2                ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.56.4               hadf4263_0    conda-forge
parso                     0.8.5              pyhcf101f3_0    conda-forge
pathlib                   1.0.1                      py_1    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_1    conda-forge
pcre2                     10.46                h1321c63_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_1    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.3.0          py312h7b42cdd_3    conda-forge
pip                       25.2               pyh8b19718_0    conda-forge
pixman                    0.46.4               h54a6638_1    conda-forge
platformdirs              4.5.0              pyhcf101f3_0    conda-forge
pluggy                    1.6.0              pyhd8ed1ab_0    conda-forge
proj                      9.7.0                hb72c0af_0    conda-forge
prometheus_client         0.23.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.52             pyha770c72_0    conda-forge
prompt_toolkit            3.0.52               hd8ed1ab_0    conda-forge
protobuf                  6.31.1          py312hb8af0ac_2    conda-forge
psutil                    7.1.0           py312h4c3975b_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
ptyprocess                0.7.0              pyhd8ed1ab_1    conda-forge
pugixml                   1.15                 h3f63f65_0    conda-forge
pulseaudio-client         17.0                 h9a8bead_2    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pydantic                  2.12.1             pyh3cfb1c2_0    conda-forge
pydantic-core             2.41.3          py312h868fb18_0    conda-forge
pygments                  2.19.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.10.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.2.5              pyhcf101f3_0    conda-forge
pyproj                    3.7.2           py312h9b6a7d9_2    conda-forge
pyside6                   6.9.3           py312h9da60e5_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
pytables                  3.10.2          py312hefc0c3f_9    conda-forge
python                    3.12.12         hfe2f287_0_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhe01879c_2    conda-forge
python-fastjsonschema     2.21.2             pyhe01879c_0    conda-forge
python-gil                3.12.12              hd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    8_cp312    conda-forge
pytorch                   2.4.0           py3.12_cuda12.4_cudnn9.1.0_0    pytorch
pytorch-cuda              12.4                 hc786d27_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2025.2             pyhd8ed1ab_0    conda-forge
pywavelets                1.9.0           py312h4f23490_1    conda-forge
pyyaml                    6.0.3           py312h8a5da7c_0    conda-forge
pyzmq                     27.1.0          py312hfb55c3c_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
qt6-main                  6.9.3                h5c1c036_0    conda-forge
r-abind                   1.4_8             r45hc72bb7e_1    conda-forge
r-askpass                 1.2.1             r45h54b55ab_1    conda-forge
r-base                    4.5.1                h14df4e6_3    conda-forge
r-base64enc               0.1_3           r45h54b55ab_1008    conda-forge
r-bslib                   0.9.0             r45hc72bb7e_1    conda-forge
r-cachem                  1.1.0             r45h54b55ab_2    conda-forge
r-class                   7.3_23            r45h54b55ab_1    conda-forge
r-classint                0.4_11            r45heaba542_1    conda-forge
r-cli                     3.6.5             r45h3697838_1    conda-forge
r-codetools               0.2_20            r45hc72bb7e_2    conda-forge
r-colorspace              2.1_2             r45h54b55ab_0    conda-forge
r-colourvalues            0.3.9             r45h3697838_3    conda-forge
r-cols4all                0.9               r45hc72bb7e_1    conda-forge
r-commonmark              2.0.0             r45h54b55ab_1    conda-forge
r-cpp11                   0.5.2             r45h785f33e_2    conda-forge
r-crayon                  1.5.3             r45hc72bb7e_2    conda-forge
r-crosstalk               1.2.2             r45hc72bb7e_1    conda-forge
r-curl                    7.0.0             r45h10955f1_1    conda-forge
r-data.table              1.17.8            r45h1c8cec4_1    conda-forge
r-dbi                     1.2.3             r45hc72bb7e_2    conda-forge
r-dichromat               2.0_0.1           r45ha770c72_4    conda-forge
r-digest                  0.6.37            r45h3697838_1    conda-forge
r-dplyr                   1.1.4             r45h3697838_2    conda-forge
r-e1071                   1.7_16            r45h3697838_1    conda-forge
r-ellipsis                0.3.2             r45h54b55ab_4    conda-forge
r-evaluate                1.0.5             r45hc72bb7e_1    conda-forge
r-fansi                   1.0.6             r45h54b55ab_2    conda-forge
r-farver                  2.1.2             r45h3697838_2    conda-forge
r-fastmap                 1.2.0             r45h3697838_2    conda-forge
r-fontawesome             0.5.3             r45hc72bb7e_1    conda-forge
r-fs                      1.6.6             r45h3697838_1    conda-forge
r-generics                0.1.4             r45hc72bb7e_1    conda-forge
r-geojsonsf               2.0.3             r45h3697838_5    conda-forge
r-geometries              0.2.4             r45h3697838_2    conda-forge
r-ggplot2                 4.0.0             r45h785f33e_0    conda-forge
r-glue                    1.8.0             r45h54b55ab_1    conda-forge
r-googlepolylines         0.8.7             r45h3697838_1    conda-forge
r-gridextra               2.3             r45hc72bb7e_1007    conda-forge
r-gtable                  0.3.6             r45hc72bb7e_1    conda-forge
r-highr                   0.11              r45hc72bb7e_2    conda-forge
r-htmltools               0.5.8.1           r45h3697838_2    conda-forge
r-htmlwidgets             1.6.4             r45h785f33e_4    conda-forge
r-httpuv                  1.6.16            r45h6d565e7_1    conda-forge
r-httr                    1.4.7             r45hc72bb7e_2    conda-forge
r-isoband                 0.2.7             r45h3697838_4    conda-forge
r-jquerylib               0.1.4             r45hc72bb7e_4    conda-forge
r-jsonify                 1.2.2             r45h3697838_3    conda-forge
r-jsonlite                2.0.0             r45h54b55ab_1    conda-forge
r-kernsmooth              2.23_26           r45ha0a88a1_1    conda-forge
r-knitr                   1.50              r45hc72bb7e_1    conda-forge
r-labeling                0.4.3             r45hc72bb7e_2    conda-forge
r-later                   1.4.4             r45h3697838_1    conda-forge
r-lattice                 0.22_7            r45h54b55ab_1    conda-forge
r-lazyeval                0.2.2             r45h54b55ab_6    conda-forge
r-leafem                  0.2.5             r45h785f33e_1    conda-forge
r-leafgl                  0.2.2             r45hc72bb7e_2    conda-forge
r-leaflegend              1.2.1             r45hc72bb7e_2    conda-forge
r-leaflet                 2.2.3             r45hc72bb7e_0    conda-forge
r-leaflet.providers       2.0.0             r45hc72bb7e_2    conda-forge
r-leafsync                0.1.0             r45hc72bb7e_5    conda-forge
r-lifecycle               1.0.4             r45hc72bb7e_2    conda-forge
r-logger                  0.4.1             r45hc72bb7e_0    conda-forge
r-lwgeom                  0.2_14            r45h6885137_8    conda-forge
r-magrittr                2.0.4             r45h54b55ab_0    conda-forge
r-mapdeck                 0.3.5             r45h3697838_3    conda-forge
r-maptiles                0.10.0            r45hc72bb7e_1    conda-forge
r-mass                    7.3_65            r45h54b55ab_0    conda-forge
r-memoise                 2.0.1             r45hc72bb7e_4    conda-forge
r-mime                    0.13              r45h54b55ab_1    conda-forge
r-munsell                 0.5.1             r45hc72bb7e_2    conda-forge
r-openssl                 2.3.4             r45h50f7d53_0    conda-forge
r-pillar                  1.11.1            r45hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r45hc72bb7e_5    conda-forge
r-plyr                    1.8.9             r45h3697838_3    conda-forge
r-png                     0.1_8             r45h6b2d295_3    conda-forge
r-promises                1.3.3             r45h3697838_1    conda-forge
r-proxy                   0.4_27            r45h54b55ab_4    conda-forge
r-purrr                   1.1.0             r45h54b55ab_1    conda-forge
r-r6                      2.6.1             r45hc72bb7e_1    conda-forge
r-rapidjsonr              1.2.0             r45hc72bb7e_5    conda-forge
r-rappdirs                0.3.3             r45h54b55ab_4    conda-forge
r-raster                  3.6_32            r45h3697838_2    conda-forge
r-rcolorbrewer            1.1_3             r45h785f33e_4    conda-forge
r-rcpp                    1.1.0             r45h3697838_1    conda-forge
r-rlang                   1.1.6             r45h3697838_1    conda-forge
r-rmarkdown               2.30              r45hc72bb7e_0    conda-forge
r-rnaturalearth           1.1.0             r45hc72bb7e_1    conda-forge
r-rnaturalearthdata       1.0.0             r45h785f33e_3    conda-forge
r-s2                      1.1.9             r45h7d5736c_3    conda-forge
r-s7                      0.2.0             r45h54b55ab_1    conda-forge
r-sass                    0.4.10            r45h3697838_1    conda-forge
r-scales                  1.4.0             r45hc72bb7e_1    conda-forge
r-servr                   0.32              r45hc72bb7e_1    conda-forge
r-sf                      1.0_21            r45h0f21de1_1    conda-forge
r-sfheaders               0.4.4             r45h3697838_2    conda-forge
r-shiny                   1.11.1            r45h785f33e_1    conda-forge
r-slippymath              0.3.1             r45hc72bb7e_5    conda-forge
r-sourcetools             0.1.7_1           r45h3697838_3    conda-forge
r-sp                      2.2_0             r45h54b55ab_1    conda-forge
r-spacesxyz               1.6_0             r45hc72bb7e_1    conda-forge
r-stars                   0.6_8             r45hc72bb7e_1    conda-forge
r-stringdist              0.9.15            r45h54b55ab_1    conda-forge
r-sys                     3.4.3             r45h54b55ab_1    conda-forge
r-terra                   1.8_70            r45h0f21de1_1    conda-forge
r-tibble                  3.3.0             r45h54b55ab_1    conda-forge
r-tidyselect              1.2.1             r45hc72bb7e_2    conda-forge
r-tinytex                 0.57              r45hc72bb7e_1    conda-forge
r-tmap                    4.2               r45hc72bb7e_0    conda-forge
r-tmaptools               3.3               r45hc72bb7e_1    conda-forge
r-units                   1.0_0             r45h3697838_0    conda-forge
r-utf8                    1.2.6             r45h54b55ab_1    conda-forge
r-vctrs                   0.6.5             r45h3697838_2    conda-forge
r-viridis                 0.6.5             r45hc72bb7e_2    conda-forge
r-viridislite             0.4.2             r45hc72bb7e_3    conda-forge
r-withr                   3.0.2             r45hc72bb7e_1    conda-forge
r-wk                      0.9.4             r45h3697838_2    conda-forge
r-xfun                    0.53              r45h3697838_1    conda-forge
r-xml                     3.99_0.17         r45hf705907_4    conda-forge
r-xtable                  1.8_4             r45hc72bb7e_7    conda-forge
r-yaml                    2.3.10            r45h54b55ab_1    conda-forge
rav1e                     0.7.1                h8fae777_3    conda-forge
re2                       2025.08.12           h5301d42_1    conda-forge
readline                  8.2                  h8c095d6_2    conda-forge
referencing               0.37.0             pyhcf101f3_0    conda-forge
requests                  2.32.5             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0              pyhd8ed1ab_1    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_1    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rfc3987-syntax            1.1.0              pyhe01879c_1    conda-forge
rpds-py                   0.27.1          py312h868fb18_1    conda-forge
s3transfer                0.14.0             pyhd8ed1ab_0    conda-forge
scikit-image              0.25.2          py312hf79963d_2    conda-forge
scikit-learn              1.7.2           py312h4f0b9e3_0    conda-forge
scipy                     1.16.2          py312h7a1785b_0    conda-forge
sdl2                      2.32.56              h54a6638_0    conda-forge
sdl3                      3.2.24               h68140b3_0    conda-forge
sed                       4.9                  h6688a6e_0    conda-forge
send2trash                1.8.3              pyh0d859eb_1    conda-forge
sentinelhub               3.11.3             pyhd8ed1ab_0    conda-forge
sentry-sdk                2.41.0             pyhd8ed1ab_0    conda-forge
setproctitle              1.3.6           py312h66e93f0_0    conda-forge
setuptools                80.9.0             pyhff2d567_0    conda-forge
shaderc                   2025.4               h3e344bc_0    conda-forge
shapely                   2.1.2           py312h950be2a_0    conda-forge
six                       1.17.0             pyhe01879c_1    conda-forge
smmap                     5.0.2              pyhd8ed1ab_0    conda-forge
snappy                    1.2.2                h03e3b7b_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_1    conda-forge
soupsieve                 2.8                pyhd8ed1ab_0    conda-forge
spirv-tools               2025.4               hb700be7_0    conda-forge
sqlite                    3.50.4               hbc0de68_0    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
svt-av1                   3.1.2                hecca717_0    conda-forge
sympy                     1.14.0           pyh2585a3b_105    conda-forge
sysroot_linux-64          2.34                 h087de78_2    conda-forge
tbb                       2021.13.0            hb60516a_3    conda-forge
tensorboard               2.20.0             pyhe01879c_0    conda-forge
tensorboard-data-server   0.7.0           py312hee9fe19_3    conda-forge
terminado                 0.18.1             pyh0d859eb_0    conda-forge
threadpoolctl             3.6.0              pyhecae5ae_0    conda-forge
tifffile                  2025.10.4          pyhd8ed1ab_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_hd72426e_102    conda-forge
tktable                   2.10                 h8d826fa_7    conda-forge
tomli                     2.3.0              pyhcf101f3_0    conda-forge
tomli-w                   1.2.0              pyhd8ed1ab_0    conda-forge
torchaudio                2.4.0               py312_cu124    pytorch
torchtriton               3.0.0                     py312    pytorch
torchvision               0.19.0              py312_cu124    pytorch
tornado                   6.5.2           py312h4c3975b_1    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
trove-classifiers         2025.9.11.17       pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20251008     pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_2    conda-forge
typing-extensions         4.15.0               h396c80c_0    conda-forge
typing-inspection         0.4.2              pyhd8ed1ab_0    conda-forge
typing_extensions         4.15.0             pyhcf101f3_0    conda-forge
typing_inspect            0.9.0              pyhd8ed1ab_1    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_1    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
unicodedata2              16.0.0          py312h4c3975b_1    conda-forge
uri-template              1.3.0              pyhd8ed1ab_1    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.5.0              pyhd8ed1ab_0    conda-forge
utm                       0.7.0              pyhd8ed1ab_0    conda-forge
wandb                     0.22.2          py312h0ccc70a_0    conda-forge
wayland                   1.24.0               h3e06ad9_0    conda-forge
wayland-protocols         1.45                 hd8ed1ab_0    conda-forge
wcwidth                   0.2.14             pyhd8ed1ab_0    conda-forge
webcolors                 24.11.1            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_3    conda-forge
websocket-client          1.9.0              pyhd8ed1ab_0    conda-forge
werkzeug                  3.1.3              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.14             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xcb-util                  0.4.1                h4f16b4b_2    conda-forge
xcb-util-cursor           0.1.5                hb9d3cd8_0    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xerces-c                  3.2.5                h988505b_2    conda-forge
xkeyboard-config          2.46                 hb03c661_0    conda-forge
xorg-libice               1.1.2                hb9d3cd8_0    conda-forge
xorg-libsm                1.2.6                he73a12e_0    conda-forge
xorg-libx11               1.8.12               h4f16b4b_0    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-libxcomposite        0.4.6                hb9d3cd8_2    conda-forge
xorg-libxcursor           1.2.3                hb9d3cd8_0    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.2                hb03c661_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxrandr            1.5.4                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.12               hb9d3cd8_0    conda-forge
xorg-libxscrnsaver        1.2.4                hb9d3cd8_0    conda-forge
xorg-libxt                1.3.1                hb9d3cd8_0    conda-forge
xorg-libxtst              1.2.5                hb9d3cd8_3    conda-forge
xorg-libxxf86vm           1.1.6                hb9d3cd8_0    conda-forge
yaml                      0.2.5                h280c20c_3    conda-forge
zeromq                    4.3.5                h387f397_9    conda-forge
zfp                       1.0.1                h909a3a2_3    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zlib-ng                   2.2.5                hde8ca8f_0    conda-forge
zstandard                 0.25.0          py312h5253ce2_0    conda-forge
zstd                      1.5.7                hb8e6e7a_2    conda-forge

```
